### ISSUE TITLE
I can't install

### ISSUE THREAD

**Issue by luhua98989898** [jiashunzheng/Lenovo_Yoga_720_Hackintosh#1]
Can you send the latest efi ？ I want to install big sur！ Thanks

**Comment by jiashunzheng** [comment]
Just uploaded a bigsur branch, check it out.

**Comment by luhua98989898** [comment]
And  can i use the 4K screen with the EFI

**Comment by luhua98989898** [comment]
> Just uploaded a bigsur branch, check it out.

When can you upload it？i want use it！thanks！

**Comment by jiashunzheng** [comment]
Check out the bigsur branch.

**Comment by jiashunzheng** [comment]
Also you probably don't have the CFG lock disabled so you need to enable additional options. (CHECK THE README)

**Comment by jiashunzheng** [comment]
> And can i use the 4K screen with the EFI

Not tested with external monitor

**Comment by luhua98989898** [comment]
> > And can i use the 4K screen with the EFI
> 
> Not tested with external monitor

No no  how much the HZ？60HZ？ Or 48hz.？

**Comment by luhua98989898** [comment]
> Check out the bigsur branch.

Big sur branch？ Which webside？ Can't see it

**Comment by jiashunzheng** [comment]
git clone git@github.com:jiashunzheng/Lenovo_Yoga_720_Hackintosh.git
git checkout bigsur

**Comment by luhua98989898** [comment]
> git clone [git@github.com](mailto:git@github.com):jiashunzheng/Lenovo_Yoga_720_Hackintosh.git
> git checkout bigsur

Send you email？ I'm in China  something i can't understand, can you send it to my email  zhangluhua989898@163.com   thanks！！

**Comment by jiashunzheng** [comment]
使用git clone 命令 git clone git@github.com:jiashunzheng/Lenovo_Yoga_720_Hackintosh.git
或者下载 zip文件，但是需要用git checkout bigsur转换到bigsur分支。

**Comment by luhua98989898** [comment]
> 使用git clone 命令 git clone [git@github.com](mailto:git@github.com):jiashunzheng/Lenovo_Yoga_720_Hackintosh.git
> 或者下载 zip文件，但是需要用git checkout bigsur转换到bigsur分支。

How do？ I don't know 怎么操作？ 我不知道怎么弄 没有直接压缩好的吗？发到zhangluhua989898@163.com  how do it？thanks！

**Comment by luhua98989898** [comment]
> > 使用git clone 命令 git clone [git@github.com](mailto:git@github.com):jiashunzheng/Lenovo_Yoga_720_Hackintosh.git
> > 或者下载 zip文件，但是需要用git checkout bigsur转换到bigsur分支。
> 
> How do？ I don't know 怎么操作？ 我不知道怎么弄 没有直接压缩好的吗？发到[zhangluhua989898@163.com](mailto:zhangluhua989898@163.com) how do it？thanks！

I got it！ Download it, can i use it directly？ What need do it

**Comment by luhua98989898** [comment]
New question. I haved send the eami you  the pic

**Comment by luhua98989898** [comment]
IDConsolelsers: tine(8) e->8.lin в. llk 1,
1OConЗolelЗers: qI0ScrВenLockState З,  hs  0, bs 0., now 0, sn Ox0 
 S5MCLightSersorTalsd: e No iterator
AppleActuatorDevicLseГClient::start  Entered
 ippleActutorDeviceUserCllent::start Entered 
Not adding subsrript ion due to nissing boot-arg lan.lorsubscrlptlons
 O8B211Virtual Interfoc::init SUCCESS _controller is 0xf6697fb960d9c055b, provlder ls 8xf 697fb96Gd9f 1edb



Stop here ？ How solve it？

**Comment by jiashunzheng** [comment]
不清楚什么原因，有可能是CFG locked导致，需要修改config.plist，[看这里](https://github.com/jiashunzheng/Lenovo_Yoga_720_Hackintosh/blob/bigsur_cfglocked/cfg_locked_patch.png)

**Comment by luhua98989898** [comment]
> 不清楚什么原因，有可能是CFG locked导致，需要修改config.plist，[看这里](https://github.com/jiashunzheng/Lenovo_Yoga_720_Hackintosh/blob/bigsur_cfglocked/cfg_locked_patch.png)

我已经打开了 要不会卡EB 那个错误应该是卡显卡！ 我现在就剩下核显驱动不了 用你的efi进不去 就是卡那里

**Comment by jiashunzheng** [comment]
你的cpu和显卡是什么型号？是独显吗？

**Comment by luhua98989898** [comment]
> 你的cpu和显卡是什么型号？是独显吗？

配置跟你一模一样的呀 要不我也不会问你

**Comment by jiashunzheng** [comment]
同样是lenovo yoga 720 15Ikb也是有很多配置的，我的是内置显卡HD630, 屏幕是1080p，你的如果是nvidia的显卡的话配置应该是不一样的。

**Comment by luhua98989898** [comment]
配置是7700HQ 有独显！ 不过我在bios设置的是核显模式！就那个UMA模式！ 屏幕是4K的

**Comment by luhua98989898** [comment]
现在就剩下核显不知道怎么弄了，用了0X591B0000 好像不起作用 你有别的联系方法吗？我在线请教你一下

**Comment by jiashunzheng** [comment]
我没有调试过带独显的版本，没办法提供更多帮助。可能需要屏蔽独显后核显才能正常工作。
https://dortania.github.io/OpenCore-Install-Guide/extras/spoof.html#windows-gpu-selection

其中最简单的是在boot-flag里（config.plist) 
加-wegnoegpu
