### ISSUE TITLE
what is your version of trackpad?

### ISSUE THREAD

**Issue by neerajverma04** [jiashunzheng/Lenovo_Yoga_720_Hackintosh#2]
i have lenovo 720 12ikb trackpad elan 0602.
i havent used your efi but mine able to start fine.. just trackpad not working.  can you verify the version you have? maybe i can follow your guide to get it working if its the same.

thanks

**Comment by neerajverma04** [comment]
I have added your files and settings in my config.plist... mouse seems to work but have issue with 1 figure touch click or 2 finger touch right click. 2 finger work for scrolling and 3 figure gesture works too. Clicking button on anyside of touchpad work as right click.

Any idea how to fix or you have same issue?
Going to settings for mouse and touchpad show nothing. Like mouse is not even connected.

**Comment by jiashunzheng** [comment]
My trackpad is ELAN 0651. I don't have the problem you described here. However, the touch and feel of the touchpad are certainly a lot different from a real Macbook trackpad.

**Comment by neerajverma04** [comment]
Thanks for the reply... Do you have some clue to fix my trackpad guesture issues?

**Comment by neerajverma04** [comment]
Can you share your updated efi for bigsur... Maybe I can try that beside catalina

**Comment by jiashunzheng** [comment]
Checkout the bigsur branch
